import { Insurer, InsuranceOffer } from "../types/insurance";

export const INSURERS: Insurer[] = [
    {
        id: "1",
        name: "L'Africaine des Assurances",
        slug: "africaine-assurances",
        logo: "/images/partners/africaine-assurance.png",
        description: "Leader historique en IARD au Bénin.",
        categories: ["IARDT", "VIE"],
        website: "https://www.africaine-assur.com/",
    },
    {
        id: "2",
        name: "SanlamAllianz",
        slug: "sanlam-allianz",
        logo: "/images/partners/sanlam-allianz.png",
        description: "Leader panafricain en assurances.",
        categories: ["IARDT", "VIE"],
        website: "https://bj.sanlamallianz.com/",
    },
    {
        id: "3",
        name: "SUNU Assurances",
        slug: "sunu-assurances",
        logo: "/images/partners/sunu_assurance.png",
        description: "Expertise régionale reconnue.",
        categories: ["IARDT", "VIE"],
        website: "https://sunuassurances.com/ci/",
    },
    {
        id: "4",
        name: "NSIA Assurances",
        slug: "nsia-assurances",
        logo: "/images/partners/nsia-assurance.png",
        description: "Vrai visage de l'assurance.",
        categories: ["IARDT", "VIE"],
        website: "https://groupensia.com",
    },
    {
        id: "5",
        name: "NOBILA Assurances",
        slug: "nobila-assurances",
        logo: "/images/partners/nobila-assurance.png",
        description: "Acteur dynamique du marché.",
        categories: ["IARDT"],
        website: "https://nobilaassurances.com/",
    },
    {
        id: "6",
        name: "CIF Vie Assurances",
        slug: "cif-vie-assurances",
        logo: "/images/partners/cif_assurances_vie.png",
        description: "Spécialiste de l'assurance vie et prévoyance.",
        categories: ["VIE"],
        website: "#",
    },
    {
        id: "7",
        name: "AFG Assurances",
        slug: "afg-assurances",
        logo: "/images/partners/afg-assurances.png",
        description: "Spécialiste voyage et IARD avec couverture internationale.",
        categories: ["IARDT", "VIE"],
        website: "#",
    },
    {
        id: "8",
        name: "GAB Assurances",
        slug: "gab-assurances",
        logo: "/images/partners/gab.png",
        description: "Assureur généraliste, dommages et responsabilité.",
        categories: ["IARDT"],
        website: "#",
    },
];

// ─────────────────────────────────────────────────────────────────────────────
//  IARDT – Assurances Dommages & Responsabilité
// ─────────────────────────────────────────────────────────────────────────────

export const IARDT_TYPES = [
    "Tous",
    "Assurance Automobile",
    "Assurance Moto",
    "Assurance Flotte",
    "Multirisque Habitation",
    "Multirisque Professionnelle",
    "Assurance Transport",
    "Responsabilité Civile",
];

export const PERSONNES_TYPES = [
    "Tous",
    "Assurance Santé",
    "Individuelle Accident",
    "Assurance Voyage",
];

export const VIE_TYPES = [
    "Tous",
    "Épargne & Retraite",
    "Assurance Éducation",
    "Assurance Emprunteur",
    "Assurance Obsèques",
];

// ─────────────────────────────────────────────────────────────────────────────
export const MOCK_OFFERS: InsuranceOffer[] = [

    // ── IARDT • Automobile ────────────────────────────────────────────────────
    // Tarifs réels Zone Rouge, 7-10CV, Promenade & Affaires, 1 AN

    {
        id: "auto-africaine",
        category: "IARDT",
        insuranceType: "Assurance Automobile",
        insuranceSubType: "Véhicules et Mobilité",
        insurer: "L'Africaine des Assurances",
        insurerSlug: "africaine-assurances",
        premium: 54632,
        coverageAmount: 10000000,
        franchise: 0,
        guarantees: ["Responsabilité Civile", "Défense et Recours", "Individuelle Accident"],
        optionalGuarantees: ["Vol", "Incendie", "Bris de Glace", "Tous Risques"],
        exclusions: ["Conduite en état d'ivresse", "Absence de permis"],
        duration: "1 à 12 mois",
        waitingPeriod: "Immédiat",
        terms: "Tarif officiel Zone Rouge, 7-10CV, usage Promenade & Affaires. RC obligatoire au Bénin.",
        rating: 4.0,
        isMandatory: true,
        tag: "Meilleur Prix",
    },
    {
        id: "auto-nobila",
        category: "IARDT",
        insuranceType: "Assurance Automobile",
        insuranceSubType: "Véhicules et Mobilité",
        insurer: "NOBILA Assurances",
        insurerSlug: "nobila-assurances",
        premium: 64609,
        coverageAmount: 10000000,
        franchise: 0,
        guarantees: ["Responsabilité Civile", "Défense et Recours", "Individuelle Accident", "Couverture CEDEAO"],
        optionalGuarantees: ["Vol", "Incendie", "Bris de Glace", "Tous Risques"],
        exclusions: ["Conduite sans permis", "Usage non conforme"],
        duration: "1 à 12 mois",
        waitingPeriod: "Immédiat",
        terms: "TALD 2025, Zone Rouge, 7-10CV, S1/C1. Inclut couverture CEDEAO (zone d'intégration régionale).",
        rating: 3.8,
        isMandatory: true,
        tag: "CEDEAO Incluse",
    },
    {
        id: "auto-sanlam",
        category: "IARDT",
        insuranceType: "Assurance Automobile",
        insuranceSubType: "Véhicules et Mobilité",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 54633,
        coverageAmount: 10000000,
        franchise: 25000,
        guarantees: ["Responsabilité Civile", "Défense et Recours", "Individuelle Accident"],
        optionalGuarantees: ["Vol", "Incendie", "Bris de Glace", "Tous Risques"],
        exclusions: ["Conduite en état d'ivresse", "Absence de permis"],
        duration: "12 mois",
        waitingPeriod: "Immédiat",
        terms: "Tarif CIMA Zone Rouge, 7-10CV. Réseau panafricain d'assistance.",
        rating: 4.5,
        isMandatory: true,
        tag: "Top Choix",
    },
    {
        id: "auto-sunu",
        category: "IARDT",
        insuranceType: "Assurance Automobile",
        insuranceSubType: "Véhicules et Mobilité",
        insurer: "SUNU Assurances",
        insurerSlug: "sunu-assurances",
        premium: 54633,
        coverageAmount: 8000000,
        franchise: 30000,
        guarantees: ["Responsabilité Civile", "Individuelle Accident"],
        optionalGuarantees: ["Accident Corporel", "Bris de Glace", "Incendie"],
        exclusions: ["Usage non conforme", "Conduite sans permis"],
        duration: "12 mois",
        waitingPeriod: "Immédiat",
        terms: "Contrat flexible avec option de résiliation mensuelle.",
        rating: 4.2,
        isMandatory: true,
        tag: "Populaire",
    },
    {
        id: "auto-nsia",
        category: "IARDT",
        insuranceType: "Assurance Automobile",
        insuranceSubType: "Véhicules et Mobilité",
        insurer: "NSIA Assurances",
        insurerSlug: "nsia-assurances",
        premium: 63859,
        coverageAmount: 15000000,
        franchise: 20000,
        guarantees: ["Responsabilité Civile", "Vol", "Incendie", "Bris de Glace", "Défense et Recours"],
        optionalGuarantees: ["Assistance Route 24h/7j", "Franchise Rachetée"],
        exclusions: ["Compétitions sportives", "Transport de matières dangereuses"],
        duration: "12 mois",
        waitingPeriod: "Immédiat",
        terms: "Tarif CIMA 11-14CV, Zone Rouge. Formule Tous Risques Premium – couverture étendue.",
        rating: 4.7,
        isMandatory: true,
        tag: "Recommandé",
    },

    // ── IARDT • Moto ──────────────────────────────────────────────────────────
    // Tarifs réels 1 AN

    {
        id: "moto-africaine",
        category: "IARDT",
        insuranceType: "Assurance Moto",
        insuranceSubType: "Véhicules et Mobilité",
        insurer: "L'Africaine des Assurances",
        insurerSlug: "africaine-assurances",
        premium: 14772,
        coverageAmount: 5000000,
        franchise: 0,
        guarantees: ["Responsabilité Civile", "Accident Corporel Conducteur"],
        optionalGuarantees: ["Vol", "Incendie"],
        exclusions: ["Conduite sans casque", "Absence de permis A"],
        duration: "12 mois",
        waitingPeriod: "Immédiat",
        terms: "Tarif réel L'Africaine, Zone Rouge. Couverture moto particuliers et utilitaires.",
        rating: 4.0,
        isMandatory: true,
        tag: "Meilleur Prix",
    },
    {
        id: "moto-nobila",
        category: "IARDT",
        insuranceType: "Assurance Moto",
        insuranceSubType: "Véhicules et Mobilité",
        insurer: "NOBILA Assurances",
        insurerSlug: "nobila-assurances",
        premium: 17303,
        coverageAmount: 3000000,
        franchise: 0,
        guarantees: ["Responsabilité Civile"],
        optionalGuarantees: ["Accident Corporel Conducteur", "Vol"],
        exclusions: ["Usage commercial non déclaré"],
        duration: "12 mois",
        waitingPeriod: "Immédiat",
        terms: "Tarif standard CIMA 2 roues, conforme au code CIMA.",
        rating: 3.8,
        isMandatory: true,
    },
    {
        id: "moto-sanlam",
        category: "IARDT",
        insuranceType: "Assurance Moto",
        insuranceSubType: "Véhicules et Mobilité",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 17303,
        coverageAmount: 4000000,
        franchise: 0,
        guarantees: ["Responsabilité Civile", "Défense et Recours"],
        optionalGuarantees: ["Accident Corporel Conducteur", "Vol", "Incendie"],
        exclusions: ["Conduite sans casque", "Absence de permis"],
        duration: "12 mois",
        waitingPeriod: "Immédiat",
        terms: "Formule complète deux roues avec options flexibles.",
        rating: 4.3,
        isMandatory: true,
        tag: "Populaire",
    },

    // ── IARDT • Flotte ────────────────────────────────────────────────────────

    {
        id: "flotte-1",
        category: "IARDT",
        insuranceType: "Assurance Flotte",
        insuranceSubType: "Véhicules et Mobilité",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 300000,
        coverageAmount: 50000000,
        franchise: 50000,
        guarantees: ["Responsabilité Civile", "Vol", "Incendie", "Dommages Collision", "Défense et Recours"],
        optionalGuarantees: ["Assistance Route", "Bris de Glace Flotte"],
        exclusions: ["Surcharge avérée", "Conduite sans permis"],
        duration: "12 mois",
        waitingPeriod: "15 jours",
        terms: "Contrat flotte à partir de 5 véhicules. Tarification dégressif selon taille.",
        rating: 4.6,
        tag: "Entreprises",
    },

    // ── IARDT • Biens et Activité ─────────────────────────────────────────────

    {
        id: "mrh-1",
        category: "IARDT",
        insuranceType: "Multirisque Habitation",
        insuranceSubType: "Biens et Activité",
        insurer: "NSIA Assurances",
        insurerSlug: "nsia-assurances",
        premium: 35000,
        coverageAmount: 20000000,
        franchise: 15000,
        guarantees: ["Incendie", "Dégât des Eaux", "Vol avec Effraction", "Catastrophes Naturelles"],
        optionalGuarantees: ["Responsabilité Civile Locataire", "Bris de Glace", "Électronique"],
        exclusions: ["Défaut d'entretien manifeste", "Guerre et émeutes"],
        duration: "12 mois",
        waitingPeriod: "30 jours",
        terms: "Protection logement et contenu. Valeur à neuf possible.",
        rating: 4.4,
        tag: "Top Choix",
    },
    {
        id: "mrh-2",
        category: "IARDT",
        insuranceType: "Multirisque Habitation",
        insuranceSubType: "Biens et Activité",
        insurer: "SUNU Assurances",
        insurerSlug: "sunu-assurances",
        premium: 28000,
        coverageAmount: 15000000,
        franchise: 20000,
        guarantees: ["Incendie", "Vol avec Effraction", "Dégât des Eaux"],
        optionalGuarantees: ["Catastrophes Naturelles", "RC Chef de Famille"],
        exclusions: ["Logement non occupé > 60 jours"],
        duration: "12 mois",
        waitingPeriod: "30 jours",
        terms: "Formule économique idéale pour locataires.",
        rating: 4.0,
        tag: "Économique",
    },
    {
        id: "mrp-1",
        category: "IARDT",
        insuranceType: "Multirisque Professionnelle",
        insuranceSubType: "Biens et Activité",
        insurer: "L'Africaine des Assurances",
        insurerSlug: "africaine-assurances",
        premium: 120000,
        coverageAmount: 50000000,
        franchise: 50000,
        guarantees: ["Incendie Bureaux & Stocks", "Vol", "Dommages Machines", "RC Exploitation"],
        optionalGuarantees: ["Pertes d'Exploitation", "Cyber Risques"],
        exclusions: ["Défaut de maintenance", "Sinistre intentionnel"],
        duration: "12 mois",
        waitingPeriod: "30 jours",
        terms: "Couverture complète pour PME et entreprises. Visite de risque obligatoire.",
        rating: 4.3,
        tag: "Entreprises",
    },
    {
        id: "transport-1",
        category: "IARDT",
        insuranceType: "Assurance Transport",
        insuranceSubType: "Biens et Activité",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 80000,
        coverageAmount: 30000000,
        franchise: 100000,
        guarantees: ["Dommages Marchandises Maritime", "Vol en Transit", "Avarie Particulière"],
        optionalGuarantees: ["Couverture Aérienne", "Couverture Terrestre"],
        exclusions: ["Emballage insuffisant", "Vices propres"],
        duration: "Par voyage / 12 mois",
        waitingPeriod: "Immédiat",
        terms: "Faculté à l'importation. Couverture door-to-door disponible.",
        rating: 4.5,
    },
    {
        id: "rc-1",
        category: "IARDT",
        insuranceType: "Responsabilité Civile",
        insuranceSubType: "Biens et Activité",
        insurer: "NSIA Assurances",
        insurerSlug: "nsia-assurances",
        premium: 22000,
        coverageAmount: 10000000,
        franchise: 10000,
        guarantees: ["RC Chef de Famille", "Dommages Corporels Tiers", "Dommages Matériels Tiers"],
        optionalGuarantees: ["RC Scolaire des Enfants", "RC Professionnelle"],
        exclusions: ["Actes intentionnels", "Fautes inexcusables"],
        duration: "12 mois",
        waitingPeriod: "30 jours",
        terms: "RC Chef de famille + RC Scolaire combinées disponibles.",
        rating: 4.2,
    },

    // ── PERSONNES • Santé & Prévoyance ────────────────────────────────────────

    {
        id: "sante-1",
        category: "PERSONNES",
        insuranceType: "Assurance Santé",
        insurer: "NSIA Assurances",
        insurerSlug: "nsia-assurances",
        premium: 60000,
        coverageAmount: 5000000,
        franchise: 5000,
        guarantees: ["Consultation Médicale", "Hospitalisation", "Pharmacie", "Maternité"],
        optionalGuarantees: ["Soins Dentaires", "Optique", "Rapatriement"],
        exclusions: ["Maladies préexistantes non déclarées", "Chirurgie esthétique"],
        duration: "12 mois",
        waitingPeriod: "3 mois (maternité 9 mois)",
        terms: "Compatible avec l'AMO (Assurance Maladie Obligatoire) en vigueur au Bénin.",
        rating: 4.4,
        tag: "Populaire",
    },
    {
        id: "sante-2",
        category: "PERSONNES",
        insuranceType: "Assurance Santé",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 125000,
        coverageAmount: 1000000,
        franchise: 0.2,
        guarantees: ["Hospitalisation", "Consultations", "Pharmacie", "Soins Dentaires"],
        optionalGuarantees: ["Maternité", "Lunetterie", "Évacuation Sanitaire"],
        exclusions: ["Chirurgie esthétique", "Soins hors réseau non autorisés"],
        duration: "12 mois",
        waitingPeriod: "3 mois (Maternité: 9 mois)",
        terms: "Couverture nationale avec tiers-payant. Plafond annuel 1M.",
        rating: 4.6,
        tag: "Recommandé",
    },
    {
        id: "accident-1",
        category: "PERSONNES",
        insuranceType: "Individuelle Accident",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 25000,
        coverageAmount: 10000000,
        franchise: 0,
        guarantees: ["Capital Décès Accidentel", "Invalidité Permanente Totale", "Invalidité Partielle"],
        optionalGuarantees: ["Frais Médicaux", "Incapacité Temporaire de Travail"],
        exclusions: ["Sports extrêmes non déclarés", "Tentative de suicide"],
        duration: "12 mois",
        waitingPeriod: "Immédiat",
        terms: "Indemnisation rapide sans franchise. Capital versé aux bénéficiaires désignés.",
        rating: 4.6,
        tag: "Recommandé",
    },
    {
        id: "accident-2",
        category: "PERSONNES",
        insuranceType: "Individuelle Accident",
        insurer: "L'Africaine des Assurances",
        insurerSlug: "africaine-assurances",
        premium: 18000,
        coverageAmount: 5000000,
        franchise: 0,
        guarantees: ["Capital Décès Accidentel", "Invalidité Permanente"],
        optionalGuarantees: ["Frais Funéraires", "Frais Médicaux"],
        exclusions: ["Accidents de guerre", "Ivresse"],
        duration: "12 mois",
        waitingPeriod: "Immédiat",
        terms: "Couverture 24h/24 sur le territoire béninois et CEDEAO.",
        rating: 4.1,
    },

    // ── PERSONNES • Voyage (tarifs réels AFG Assurances) ─────────────────────
    // Primes TTC proposées pour 30 jours, âge 19-65 ans

    {
        id: "voyage-afg-afrique",
        category: "PERSONNES",
        insuranceType: "Assurance Voyage",
        insuranceSubType: "Afrique",
        insurer: "AFG Assurances",
        insurerSlug: "afg-assurances",
        premium: 14880,
        coverageAmount: 5000000,
        franchise: 0,
        guarantees: ["Frais Médicaux Urgents", "Rapatriement Sanitaire", "Assistance 24h/7j"],
        optionalGuarantees: ["Perte de Bagages", "RC à l'Étranger", "Annulation de Voyage"],
        exclusions: ["Zones de guerre déclarée", "Maladies chroniques non stabilisées"],
        duration: "7j à annuel (multi-voyages)",
        waitingPeriod: "Immédiat",
        terms: "Prime TTC pour 30 jours. Dès 7 286 F.CFA/7j jusqu'à 52 411 F.CFA/an (multi-voyages). Zone Afrique.",
        rating: 4.2,
        tag: "Afrique",
    },
    {
        id: "voyage-afg-schengen",
        category: "PERSONNES",
        insuranceType: "Assurance Voyage",
        insuranceSubType: "Schengen",
        insurer: "AFG Assurances",
        insurerSlug: "afg-assurances",
        premium: 17153,
        coverageAmount: 8000000,
        franchise: 0,
        guarantees: ["Frais Médicaux à l'Étranger", "Rapatriement Sanitaire", "Assistance 24h/7j", "RC à l'Étranger"],
        optionalGuarantees: ["Annulation de Voyage", "Retard/Perte de Bagages", "Retard de Transport"],
        exclusions: ["Zones de guerre", "Sports extrêmes non déclarés"],
        duration: "7j à annuel (multi-voyages)",
        waitingPeriod: "Immédiat",
        terms: "Obligatoire pour visa Schengen. Dès 8 513 F.CFA/7j jusqu'à 62 188 F.CFA/an. Conforme exigences consulaires.",
        rating: 4.6,
        tag: "Visa Schengen",
    },
    {
        id: "voyage-afg-europe",
        category: "PERSONNES",
        insuranceType: "Assurance Voyage",
        insuranceSubType: "Europe",
        insurer: "AFG Assurances",
        insurerSlug: "afg-assurances",
        premium: 24853,
        coverageAmount: 12000000,
        franchise: 0,
        guarantees: ["Frais Médicaux à l'Étranger", "Rapatriement Sanitaire", "Assistance 24h/7j", "RC Personnelle"],
        optionalGuarantees: ["Annulation de Voyage", "Perte de Bagages"],
        exclusions: ["Zones de conflit armé", "Maladies préexistantes non stabilisées"],
        duration: "7j à annuel (multi-voyages)",
        waitingPeriod: "Immédiat",
        terms: "Couverture Europe étendue. Dès 10 713 F.CFA/7j jusqu'à 89 688 F.CFA/an.",
        rating: 4.5,
        tag: "Europe",
    },
    {
        id: "voyage-afg-mondial-basic",
        category: "PERSONNES",
        insuranceType: "Assurance Voyage",
        insuranceSubType: "Mondial Basic",
        insurer: "AFG Assurances",
        insurerSlug: "afg-assurances",
        premium: 28353,
        coverageAmount: 20000000,
        franchise: 0,
        guarantees: ["Frais Médicaux Monde Entier", "Rapatriement Sanitaire", "Assistance 24h/7j", "RC Mondiale"],
        optionalGuarantees: ["Annulation", "Bagages", "Retard de vol"],
        exclusions: ["Zones sous embargo", "Sports extrêmes non déclarés"],
        duration: "7j à annuel (multi-voyages)",
        waitingPeriod: "Immédiat",
        terms: "Couverture mondiale. Dès 13 816 F.CFA/7j jusqu'à 105 650 F.CFA/an (multi-voyages).",
        rating: 4.4,
        tag: "Mondial Basic",
    },
    {
        id: "voyage-afg-mondial-plus",
        category: "PERSONNES",
        insuranceType: "Assurance Voyage",
        insuranceSubType: "Mondial Plus",
        insurer: "AFG Assurances",
        insurerSlug: "afg-assurances",
        premium: 30174,
        coverageAmount: 30000000,
        franchise: 0,
        guarantees: ["Frais Médicaux Monde Entier", "Rapatriement Sanitaire", "Assistance 24h/7j", "RC Mondiale", "Annulation Incluse"],
        optionalGuarantees: ["Bagages Premium", "Retard de vol", "Assistance Juridique"],
        exclusions: ["Zones sous embargo ONU"],
        duration: "7j à annuel (multi-voyages)",
        waitingPeriod: "Immédiat",
        terms: "Formule premium tout compris. Dès 16 737 F.CFA/7j jusqu'à 138 261 F.CFA/an.",
        rating: 4.8,
        tag: "Premium Mondial",
    },

    // ── PERSONNES • Voyage (autres compagnies) ────────────────────────────────

    {
        id: "voyage-sanlam",
        category: "PERSONNES",
        insuranceType: "Assurance Voyage",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 35000,
        coverageAmount: 15000000,
        franchise: 0,
        guarantees: [
            "Frais Médicaux à l'Étranger",
            "Rapatriement Sanitaire",
            "Assistance 24h/7j",
            "RC à l'Étranger",
        ],
        optionalGuarantees: [
            "Annulation de Voyage",
            "Retard/Perte de Bagages",
            "Retard de Transport",
        ],
        exclusions: ["Zones de guerre", "Sports extrêmes non déclarés"],
        duration: "Par voyage (max 90 jours)",
        waitingPeriod: "Immédiat",
        terms: "Obligatoire pour visa Schengen. Couvre assistance médicale et rapatriement.",
        rating: 4.7,
        tag: "Recommandé",
    },
    {
        id: "voyage-nsia",
        category: "PERSONNES",
        insuranceType: "Assurance Voyage",
        insurer: "NSIA Assurances",
        insurerSlug: "nsia-assurances",
        premium: 25000,
        coverageAmount: 8000000,
        franchise: 0,
        guarantees: [
            "Frais Médicaux Urgents",
            "Rapatriement",
            "Perte de Bagages",
        ],
        optionalGuarantees: [
            "Annulation de Voyage",
            "RC Personnelle à l'Étranger",
        ],
        exclusions: ["Maladies chroniques préexistantes non stabilisées"],
        duration: "Par voyage (max 60 jours)",
        waitingPeriod: "Immédiat",
        terms: "Formule économique valable pour les voyages en Afrique et Europe.",
        rating: 4.2,
        tag: "Économique",
    },

    // ── VIE • Épargne & Prévoyance Long Terme ────────────────────────────────

    {
        id: "vie-epargne-1",
        category: "VIE",
        insuranceType: "Épargne & Retraite",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 10000,
        rate: 3.5,
        coverageAmount: 5000000,
        franchise: 0,
        guarantees: ["Capital Garanti", "Participation aux Bénéfices", "Exonération Décès"],
        optionalGuarantees: ["Doublement Capital Décès Accidentel", "Avance sur Police"],
        exclusions: ["Suicide la première année"],
        duration: "Min. 8 ans (Passeport Retraite)",
        waitingPeriod: "3 mois",
        terms: "Versements mensuels à partir de 10 000 F. Droit d'entrée 1%. Récupération à l'échéance.",
        rating: 4.8,
        tag: "Recommandé",
    },
    {
        id: "vie-epargne-2",
        category: "VIE",
        insuranceType: "Épargne & Retraite",
        insurer: "NSIA Assurances",
        insurerSlug: "nsia-assurances",
        premium: 20000,
        rate: 4.0,
        coverageAmount: 10000000,
        franchise: 0,
        guarantees: ["Capital Garanti", "Rente Viagère", "Exonération Décès"],
        optionalGuarantees: ["Couverture Invalidité", "Retraite Anticipée"],
        exclusions: ["Retrait avant 5 ans – pénalité"],
        duration: "Min. 10 ans",
        waitingPeriod: "3 mois",
        terms: "Contrat épargne-retraite. Taux garanti 4% + participation bénéfices.",
        rating: 4.6,
        tag: "Top Choix",
    },
    {
        id: "vie-education-1",
        category: "VIE",
        insuranceType: "Assurance Éducation",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 8000,
        rate: 3.0,
        coverageAmount: 3000000,
        franchise: 0,
        guarantees: ["Capital Études Garanti", "Exonération en cas de Décès du Parent", "Rente Mensuelle aux Enfants"],
        optionalGuarantees: ["Doublement Décès Accidentel"],
        exclusions: ["Interruption d'études non médicale"],
        duration: "Jusqu'à la majorité de l'enfant",
        waitingPeriod: "3 mois",
        terms: "Garantit le financement des études même en cas de disparition du souscripteur.",
        rating: 4.5,
        tag: "Familles",
    },
    {
        id: "vie-education-2",
        category: "VIE",
        insuranceType: "Assurance Éducation",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 12000,
        rate: 3.5,
        coverageAmount: 5000000,
        franchise: 0,
        guarantees: ["Capital Études Garanti", "Exonération Décès du Souscripteur", "Versements à l'Enfant"],
        optionalGuarantees: ["Allocation Mensuelle Renforcée", "Couverture Frais de Scolarité"],
        exclusions: ["Abandon scolaire volontaire"],
        duration: "Jusqu'à 25 ans de l'enfant (études supérieures incluses)",
        waitingPeriod: "3 mois",
        terms: "Contrat souscrit au nom de l'enfant, géré par le tuteur.",
        rating: 4.7,
        tag: "Recommandé",
    },
    {
        id: "vie-emprunteur-1",
        category: "VIE",
        insuranceType: "Assurance Emprunteur",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 50000,
        coverageAmount: 20000000,
        franchise: 0,
        guarantees: ["Couverture Décès", "Invalidité Totale et Définitive"],
        optionalGuarantees: ["Perte d'Emploi", "Invalidité Partielle"],
        exclusions: ["Sport extrême sans déclaration"],
        duration: "Durée du prêt",
        waitingPeriod: "Immédiat",
        terms: "Assurance liée à un prêt bancaire. Tarif selon âge et montant.",
        rating: 4.4,
        tag: "Bancaire",
    },
    {
        id: "vie-obseques-1",
        category: "VIE",
        insuranceType: "Assurance Obsèques",
        insurer: "SanlamAllianz",
        insurerSlug: "sanlam-allianz",
        premium: 5000,
        coverageAmount: 2000000,
        franchise: 0,
        guarantees: ["Capital Obsèques", "Rapatriement du Corps", "Assistance Funéraire 24h/7j"],
        optionalGuarantees: ["Majoration Capital Famille", "Extension International"],
        exclusions: ["Suicide dans les 12 premiers mois"],
        duration: "Vie entière",
        waitingPeriod: "1 an",
        terms: "Soulage la famille des charges funéraires. Versement rapide sous 48h.",
        rating: 4.3,
        tag: "Sérénité",
    },
];
